// <auto-generated />
using System;
using System.Collections.Generic;
using ChatApplication.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChatApplication.Infra.Migrations
{
    [DbContext(typeof(ContextDB))]
    [Migration("20251101192603_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChatApplication.Dommain.Entities.Chat", b =>
                {
                    b.Property<Guid>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<bool>("IsGroup")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("ChatId");

                    b.ToTable("Chat");
                });

            modelBuilder.Entity("ChatApplication.Dommain.Entities.ChatUsers", b =>
                {
                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("ChatId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("chatUsers");
                });

            modelBuilder.Entity("ChatApplication.Dommain.Entities.Mensage", b =>
                {
                    b.Property<Guid>("MensageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<List<string>>("ImageMensage")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime>("SendMensage")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("MensageId");

                    b.HasIndex("ChatId");

                    b.ToTable("Mensage");
                });

            modelBuilder.Entity("ChatApplication.Dommain.Entities.MensageStatus", b =>
                {
                    b.Property<Guid>("MensageID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsReceived")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MensageId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ReaAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MensageID", "UserId");

                    b.HasIndex("MensageId");

                    b.HasIndex("UserId");

                    b.ToTable("MensageStatus");
                });

            modelBuilder.Entity("ChatApplication.Dommain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateData")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ChatApplication.Dommain.Entities.UserFriend", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FriendId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("boolean");

                    b.HasKey("UserId", "FriendId");

                    b.HasIndex("FriendId");

                    b.ToTable("UserFriend");
                });

            modelBuilder.Entity("ChatApplication.Dommain.Entities.ChatUsers", b =>
                {
                    b.HasOne("ChatApplication.Dommain.Entities.Chat", "Chat")
                        .WithMany("ChatUsers")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChatApplication.Dommain.Entities.User", "User")
                        .WithMany("ChatUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChatApplication.Dommain.Entities.Mensage", b =>
                {
                    b.HasOne("ChatApplication.Dommain.Entities.Chat", null)
                        .WithMany("Mensages")
                        .HasForeignKey("ChatId");
                });

            modelBuilder.Entity("ChatApplication.Dommain.Entities.MensageStatus", b =>
                {
                    b.HasOne("ChatApplication.Dommain.Entities.Mensage", null)
                        .WithMany()
                        .HasForeignKey("MensageID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChatApplication.Dommain.Entities.Mensage", null)
                        .WithMany("MensageStatus")
                        .HasForeignKey("MensageId");

                    b.HasOne("ChatApplication.Dommain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ChatApplication.Dommain.Entities.UserFriend", b =>
                {
                    b.HasOne("ChatApplication.Dommain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChatApplication.Dommain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ChatApplication.Dommain.Entities.Chat", b =>
                {
                    b.Navigation("ChatUsers");

                    b.Navigation("Mensages");
                });

            modelBuilder.Entity("ChatApplication.Dommain.Entities.Mensage", b =>
                {
                    b.Navigation("MensageStatus");
                });

            modelBuilder.Entity("ChatApplication.Dommain.Entities.User", b =>
                {
                    b.Navigation("ChatUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
